const webdriverIOReferences = require('@puzzel/wdio-references-async');

var commonMethods = {
    Article_Title : 'Test Article in Plain Text',
    Create_Article_Content : 'This is an article that is for test automation',
    Rich_Text_Article_Title : 'Test Article in Rich Text',
    Rich_Text_Article_Content : 'This is an article that is for test automation which is created in Rich text',
    Top_Article_Title : 'Test Article',
    Top_Article_Content: 'Making an article as a top article by clicking on star mark and is displayed in the top articles list view',
    Delete_Article_Title: 'Delete Article Test',
    Delete_Article_Content:'Creating this article to delete it',
    Add_Languages_Title: 'Article With Languages',
    Add_Languages_Content: 'This is English language article with English content',
    Norwegian_Article_Title: 'Norwegian Article',
    Norwegian_Article_Content: 'Dette er en Norsk artikkel og Ha en fin dag',
    Audience_Groups_Title: 'Audience Groups Test',
    Audience_Groups_Content: 'This is an article that is to add audience. For example : Agent and Mobile views',
    Article_Status_Title_Drafts: 'Sample article in Draft state',
    Article_Status_Content_Drafts: 'This article is created by default in drafts state',
    Article_Status_Title_Review: 'Sample article in Review state',
    Article_Status_Content_Review: 'Creating an article and set its status to Review',
    Article_Status_Title_Published: 'Published article',
    Article_Status_Content_Published: 'Creating own article and set its status to Published',
    Comment_In_Textarea: 'Saving changes to the article',
    Audience1_Name: 'Customer1',
    Audience2_Name: 'Customer2',
    Audience3_Name: 'Satya',
    Changed_Audience_Name: 'Satya SS',
    Custom_Permissions_Scheme_Name: 'Testing Automation Scheme',
    Custom_Permissions_Scheme_Descriprtion: 'This Permission Scheme is only for testing purposes only',
    Article_Title_By_Manager: 'Article to test by Manager',
    Article_Content_By_Manager: 'Lets create an new article for testing purposes only',
    Content_Edit_In_The_CKEditor: 'Editing this article as a manager',
    Tags : 'Manager,Editing,Article',
    Edited_Category_Name: 'New Category Test',
    Edited_Section_Name: 'new bee 2',
    Article_Title_By_Agent: 'Article to test by Agent',
    Article_Content_By_Agent: 'Lets create a new article for testing purposes only. This article has a slightly longer content',
    Content_Edit_In_The_CKEditor_By_Agent: 'Lets create a new article for testing purposes only. ',
    Expired_Article_Title: 'Expired Article Test',
    Expired_Article_Content: 'This is the Article that will get expired immediately. ',
    News_Article_Title: 'News Article for Test Automation',
    News_Article_Content: 'This is a news article that is very similer to regular article',
    Announcement_Article_Title: 'Announcement for Test Automation',
    Announcement_Article_Content: 'This is an announcement that is very similer to regular article but it will be displayed as banner in the Widget KB Application',
    Feedback_Text_Sent_To_Admin: 'Feedback test by an admin user, which should be displayed in the Admin view under the feedback test automation article',
    Reply_To_A_Feedback_From_Admin: 'Feedback from widget has been viewed and this a reply from Admin',

};

module.exports = commonMethods;